# Generated by Django 3.0.3 on 2020-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicturePools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, verbose_name='图片名称')),
                ('tags', models.CharField(default='动漫图片', max_length=2000, verbose_name='标签')),
                ('author', models.CharField(default='admin', max_length=80, verbose_name='作者')),
                ('stars', models.IntegerField(default=0, verbose_name='评分')),
                ('MD5', models.CharField(max_length=128, verbose_name='md5值')),
                ('mini_path', models.CharField(max_length=500, verbose_name='缩略图路径')),
                ('view_path', models.CharField(max_length=500, verbose_name='浏览图路径')),
                ('download_path', models.CharField(max_length=500, verbose_name='下载图路径')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(default='admin', max_length=20, verbose_name='修改记录')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '图片池',
                'verbose_name_plural': '图片池',
                'db_table': 'picture_pools',
            },
        ),
    ]
